### ISSUE TITLE
 Incompatibility with Firefox due to usage of :has() pseudo-class in CSS

### ISSUE THREAD

**Issue by albinkc** [WebDevSimplified/react-todo-list#4]
The custom checkbox styling does not function as expected in Firefox. The issue is caused by the utilization of the `:has() `pseudo-class in the CSS, which is not supported by Firefox yet and remains a part of the CSS Selectors Level 4 working draft. As a result, the styles relying on the :has() pseudo-class are not applied in Firefox, leading to inconsistencies in the user experience across different browsers.

The problematic CSS is shown below:
```css

.list li:has(input:checked) label {
  color: hsl(200, 20%, 40%);
}
.list li:has(input:focus-visible) label {
  outline: 1px solid hsl(200, 100%, 50%);
}
.list li:has(input:checked) label::before {
  content: "✔";
  background: hsl(200, 100%, 40%);
  color: hsl(200, 100%, 90%);
  font-size: 0.75rem;
  font-weight: bold;
}
.list li:has(input:checked) label:hover::before {
  background: hsl(200, 100%, 30%);
}
```
This leads to the checkbox state not being updated visually for Firefox users.

**Comment by albinkc** [comment]
Update:
Found a temporary fix for Firefox:

```css
.list li input {
  /* outline: none; */
  /* width: 0;
  height: 0; */
  /* appearance: none; */
  pointer-events: none;
  position: absolute;
}
```

Removing the properties shown above gives a crude but working checkbox:
<img width="790" alt="image" src="https://user-images.githubusercontent.com/8876252/236694204-99737f63-4adf-426c-9391-292fc161710b.png">

P.S: Not a CSS expert
